from turtle import Turtle, Screen
import tkinter as TK

# Object = Class()
Sammy = Turtle()
# Attributes for Sammy (Object)
print(Sammy)
Sammy.shape("turtle")
Sammy.color("midnightblue")
# Make an "I"
Sammy.left(90)
Sammy.forward(300)
Sammy.left(90)
Sammy.forward(10)
Sammy.left(90)
Sammy.forward(600)
Sammy.left(90)
Sammy.forward(20)
Sammy.left(90)
Sammy.forward(600)
Sammy.left(90)
Sammy.forward(10)
Sammy.pencolor('white')
Sammy.home()
# Make a heart
Sammy.left(90)
Sammy.forward(300)
Sammy.pencolor('DeepPink2')
Sammy.left(45)
Sammy.forward(150)
Sammy.left(45)
Sammy.forward(100)
Sammy.left(45)
Sammy.forward(350)
Sammy.left(90)
Sammy.forward(655)
Sammy.left(90)
Sammy.forward(655)
Sammy.left(90)
Sammy.forward(350)
Sammy.left(45)
Sammy.forward(100)
Sammy.left(45)


my_screen = Screen()
#Attribute and Method for Tkinter canva to stay on screen
print(my_screen.canvheight)
my_screen.exitonclick()

